quarkus:
  http:
    limits:
      max-form-size: 10M
    body:
      handle-file-uploads: false
    netty:
      receive-buffer-size: 65536
      send-buffer-size: 65536
      tcp-no-delay: true
      tcp-keep-alive: true

  vertx:
    event-loops-pool-size: 4

  thread-pool:
    core-threads: 8
    max-threads: 200
    queue-size: 10000
    shutdown-timeout: 60

  log:
    level: INFO
    category:
      "ru.rkhamatyarov":
        level: DEBUG
      "ru.rkhamatyarov.websocket":
        level: DEBUG
    

  quinoa:
    package-manager-install: true
    node-version: 24.14.0
    dev-server:
      port: 5173
  native:
    additional-build-args: >
      -H:IncludeResources=.*\\.proto,
      --initialize-at-run-time=com.google.protobuf,
      --initialize-at-run-time=ru.rkhamatyarov.proto,
      -H:+ReportExceptionStackTraces
    resources:
      includes:
        - "META-INF/resources/**"
        - ".*\\.html"
        - ".*\\.css"
        - ".*\\.js"
        - "assets/.*"
        - ".*\\.proto"
    reflection:
      include-patterns:
        - ru.rkhamatyarov.proto.**
        - com.google.protobuf.**
        
  websockets-next:
    server:
      supported-subprotocols: binary

  scheduler:
    enabled: true

remimho:
  browser:
    open: true
    url: http://localhost:8080
